version: "3.9"

networks:
  default:
    name: web_net


services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_DB=devops
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  rabbitmq:
    image: rabbitmq:alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:7
    volumes:
      - redis-data:/data

  django:
    image: embedproject:latest
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input --clear &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
      #command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=psql://user:password@db:5432
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - SECRET_KEY=i5j5(f87^%ux__9f*&w$m@&u=sp^bhxj+26u-7na06z6egieuj
      - ALLOWED_HOSTS=api.digiadam.website
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devops
      - DB_USER=user
      - DB_PASS=password
      - DB_PORT=5432

    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
      - ".:/app/backend/backend_api"
    depends_on:
      - db
      - rabbitmq
    restart: on-failure
    labels:
     - "traefik.enable=true"
     - "traefik.docker.network=web_net"
     - "traefik.http.routers.backend.entrypoints=http"
     - "traefik.http.routers.backend.rule=Host(`api.digiadam.website`)"
     - "traefik.http.routers.backend.service=backend-secure"
     - "traefik.http.routers.backend.middlewares=https-redirect"
     - "traefik.http.routers.backend-secure.entrypoints=https"
     - "traefik.http.routers.backend-secure.rule=Host(`api.digiadam.website`)"
     - "traefik.http.routers.backend-secure.tls=true"
     - "traefik.http.routers.backend-secure.tls.options=default"
     - "traefik.http.routers.backend-secure.tls.certresolver=mycert"
     - "traefik.http.routers.backend-secure.service=backend-secure"
     - "traefik.http.services.backend-secure.loadbalancer.server.port=8000"


  celery:
    image: embedproject:latest
    command: celery -A devopshobbies.tasks worker -l info --without-gossip --without-mingle --without-heartbeat
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  beats:
    image: embedproject:latest
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

volumes:
    redis-data:
    static_volume:
    media_volume: